### PR TITLE
Feature/deactivation hook

### PR DESCRIPTION
**Pull request by carlosesilva**
Delete all post meta when deactivating the plugin

### CODE REVIEW

**Review by Adam42 — APPROVED** [review]
LGTM. But I wonder if we should check if http content exists before allowing the plugin to be deactivated?

**Comment by carlosesilva** [comment]
That is a good idea @Adam42!

**Comment by carlosesilva** [comment]
In an effort to get HTTPS everywhere rolling asap I will merge this pr as is now and open an issue for the proposed enhancement.

**Comment by Adam42** [comment]
@carlosesilva I definitely intended for that to be an enhancement outside of scope of this PR so :+1:

**Pull request merged**
